# Generated by Django 2.2.7 on 2020-11-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_tenders_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='tenders',
            name='category',
            field=models.CharField(blank=True, default='tech', max_length=200, null=True),
        ),
    ]
