# Generated by Django 2.2.7 on 2020-11-18 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_auto_20201115_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='close_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tenders',
            name='open_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
