# Generated by Django 2.2.7 on 2020-11-26 09:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_auto_20201118_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenders',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
